# Generated by Django 5.0.6 on 2024-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('C', 'C'), ('Python', 'Python'), ('Java', 'Java')], default='Python', max_length=50),
        ),
    ]
