# Generated by Django 5.0.6 on 2024-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_c_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='c_answer',
            field=models.CharField(max_length=250),
        ),
    ]
