# Generated by Django 5.0.6 on 2024-07-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_mark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='verified',
        ),
    ]
