# Generated by Django 5.0.6 on 2024-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='questions',
            field=models.ManyToManyField(related_name='marks', to='quiz.question'),
        ),
    ]
