# Generated by Django 5.0.6 on 2024-07-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_definition', models.TextField(default='default_value_here', max_length=500)),
                ('hint', models.TextField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(choices=[('C', 'C'), ('Java', 'Java'), ('Python', 'Python')], default='Python', max_length=50)),
            ],
        ),
    ]
