# Generated by Django 5.0.6 on 2024-06-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
